---
application:
  name: "backend-rent-movie"
  project: "test-api"
  organization: "QoveryCommunity"
databases:
- type: "MYSQL"
  name: "mvcapp"
  version: "8.0"
routers:
- name: "main-backend-rent-movie"
  routes:
  - application_name: "backend-rent-movie"
    paths:
    - "/*"
